services:
  rng-api:
    image: adipurnomo/rng-api:21.05
    environment:
      - Logging__LogLevel__Default=Debug
    ports:
      - 8089:80
    networks:
      - app-net

  rng-web:
    image: adipurnomo/rng-web:21.05
    environment:
      - Logging__LogLevel__Default=Debug
    ports:
      - 8090:80
    networks:
      - app-net

networks:
  app-net:
